repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description : Run golangci-lint on Go files
        entry: bash -c "cd parser && golangci-lint run --config=.golangci.toml --new-from-rev HEAD --fix"
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
        verbose: true
      - id: go-test
        name: go-test
        description: Run go test on Go files
        entry: bash -c "cd parser && go test -v ./..."
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
        verbose: true
      - id: go-vet
        name: go-vet
        description: Run go vet on Go files
        entry: bash -c "cd parser && go vet ./core/... ./ffi/... ./wasm/..."
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
        verbose: true
