name: Analyzer WASM CI

on:
  push:
    branches: [ main ]
    paths:
      - 'analyzer/**'
      - 'grammar/**'
      - '.github/workflows/analyzer-ci.yml'
  pull_request:
    branches: [ '*', '!hotfix/**' ]
    paths:
      - 'analyzer/**'
      - 'grammar/**'
      - '.github/workflows/analyzer-ci.yml'

jobs:
  test-wasm:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: analyzer
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'
    
    - name: Install chrome
      uses: browser-actions/setup-chrome@v2
      with:
        chrome-version: stable
    
    - name: Install wasmbrowsertest
      run: go install github.com/agnivade/wasmbrowsertest@latest

    - name: Setup wasmexec
      run: mv $(go env GOPATH)/bin/wasmbrowsertest $(go env GOPATH)/bin/go_js_wasm_exec
    
    - name: Install xvfb for headless testing
      run: sudo apt-get update && sudo apt-get install -y xvfb

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Generate ANTLR parser
      run: ./codegen.sh

    - name: Build WASM  
      run: go build ./wasm/analyzer.go
      env:
        GOOS: js
        GOARCH: wasm

    - name: Test WASM
      run: go test ./wasm/...
      env:
        GOOS: js
        GOARCH: wasm
